using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using SuprematyDemo.Domain.Entities; using SuprematyDemo.Infrastructure.Persistence;
namespace SuprematyDemo.Api.Controllers;
[ApiController,Authorize(Roles="Admin"),Route("api/admin")] public sealed class CommerceManagementController(AppDbContext db):ControllerBase{
 [HttpGet("dashboard")] public async Task<IActionResult> Dashboard()=>Ok(new{products=await db.Products.CountAsync(),orders=await db.Orders.CountAsync(),customers=await db.Users.CountAsync(),lowStock=await db.Inventory.CountAsync(x=>x.QuantityOnHand<=x.ReorderLevel),revenue=await db.Orders.Where(x=>x.Status!="Cancelled").SumAsync(x=>(decimal?)x.Total)??0});
 [HttpGet("products")] public async Task<IActionResult> Products()=>Ok(await db.Products.OrderByDescending(x=>x.CreatedUtc).ToListAsync());
 [HttpPost("products")] public async Task<IActionResult> CreateProduct(ProductEdit x){var p=new Product(x.Name,x.Colour,x.Price){Description=x.Description??"",Sku=string.IsNullOrWhiteSpace(x.Sku)?$"SKU-{Guid.NewGuid().ToString()[..8].ToUpper()}":x.Sku,DiscountedPrice=x.DiscountedPrice,CategoryId=x.CategoryId,ImageUrl=x.ImageUrl,IsActive=x.IsActive,IsFeatured=x.IsFeatured};db.Products.Add(p);await db.SaveChangesAsync();return Ok(p);}
 [HttpPut("products/{id:guid}")] public async Task<IActionResult> UpdateProduct(Guid id,ProductEdit x){var p=await db.Products.FindAsync(id);if(p is null)return NotFound();p.Name=x.Name;p.Colour=x.Colour;p.Price=x.Price;p.Description=x.Description??"";p.Sku=x.Sku;p.DiscountedPrice=x.DiscountedPrice;p.CategoryId=x.CategoryId;p.ImageUrl=x.ImageUrl;p.IsActive=x.IsActive;p.IsFeatured=x.IsFeatured;p.UpdatedUtc=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return Ok(p);}
 [HttpDelete("products/{id:guid}")] public async Task<IActionResult> DeleteProduct(Guid id){var p=await db.Products.FindAsync(id);if(p is null)return NotFound();db.Products.Remove(p);await db.SaveChangesAsync();return NoContent();}
 [HttpGet("categories")] public async Task<IActionResult> Categories()=>Ok(await db.Categories.ToListAsync()); [HttpPost("categories")] public async Task<IActionResult> AddCategory(Category x){x.Id=Guid.NewGuid();db.Categories.Add(x);await db.SaveChangesAsync();return Ok(x);} [HttpPut("categories/{id:guid}")] public async Task<IActionResult> EditCategory(Guid id,Category x){var e=await db.Categories.FindAsync(id);if(e is null)return NotFound();e.Name=x.Name;e.Slug=x.Slug;e.IsActive=x.IsActive;await db.SaveChangesAsync();return Ok(e);} [HttpDelete("categories/{id:guid}")] public async Task<IActionResult> DeleteCategory(Guid id){var e=await db.Categories.FindAsync(id);if(e is null)return NotFound();db.Remove(e);await db.SaveChangesAsync();return NoContent();}
 [HttpGet("inventory")] public async Task<IActionResult> Inventory()=>Ok(await db.Inventory.ToListAsync()); [HttpPut("inventory/{productId:guid}")] public async Task<IActionResult> Inventory(Guid productId,InventoryEdit x){var e=await db.Inventory.SingleOrDefaultAsync(i=>i.ProductId==productId);if(e is null){e=new(){ProductId=productId};db.Inventory.Add(e);}e.QuantityOnHand=x.QuantityOnHand;e.ReorderLevel=x.ReorderLevel;e.Warehouse=x.Warehouse;e.UpdatedUtc=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return Ok(e);}
 [HttpGet("coupons")] public async Task<IActionResult> Coupons()=>Ok(await db.Coupons.ToListAsync()); [HttpPost("coupons")] public async Task<IActionResult> AddCoupon(Coupon x){x.Id=Guid.NewGuid();x.Code=x.Code.ToUpperInvariant();db.Coupons.Add(x);await db.SaveChangesAsync();return Ok(x);} [HttpPut("coupons/{id:guid}")] public async Task<IActionResult> EditCoupon(Guid id,Coupon x){var e=await db.Coupons.FindAsync(id);if(e is null)return NotFound();e.Code=x.Code.ToUpperInvariant();e.DiscountPercent=x.DiscountPercent;e.MinimumOrder=x.MinimumOrder;e.IsActive=x.IsActive;e.ExpiresUtc=x.ExpiresUtc;await db.SaveChangesAsync();return Ok(e);} [HttpDelete("coupons/{id:guid}")] public async Task<IActionResult> DeleteCoupon(Guid id){var e=await db.Coupons.FindAsync(id);if(e is null)return NotFound();db.Remove(e);await db.SaveChangesAsync();return NoContent();}
 [HttpGet("orders")] public async Task<IActionResult> Orders()=>Ok(await db.Orders.Include(x=>x.Items).OrderByDescending(x=>x.CreatedUtc).ToListAsync()); [HttpPut("orders/{id:guid}/status")] public async Task<IActionResult> Status(Guid id,StatusEdit x){var o=await db.Orders.FindAsync(id);if(o is null)return NotFound();var allowed=new[]{"Pending","Confirmed","Processing","Shipped","Delivered","Cancelled","Refunded"};if(!allowed.Contains(x.Status))return BadRequest("Invalid status");o.Status=x.Status;if(x.Status=="Delivered")o.DeliveredUtc=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return Ok(o);} [HttpDelete("orders/{id:guid}")] public async Task<IActionResult> DeleteOrder(Guid id){var o=await db.Orders.FindAsync(id);if(o is null)return NotFound();db.Remove(o);await db.SaveChangesAsync();return NoContent();}
 [HttpGet("customers")] public async Task<IActionResult> Customers()=>Ok(await db.Users.Select(x=>new{x.Id,x.Email,x.DisplayName,x.CreatedUtc}).ToListAsync());
 public record ProductEdit(string Name,string Colour,decimal Price,string Sku,string? Description,decimal? DiscountedPrice,Guid? CategoryId,string? ImageUrl,bool IsActive=true,bool IsFeatured=false); public record InventoryEdit(int QuantityOnHand,int ReorderLevel,string Warehouse); public record StatusEdit(string Status);
}
