using System.Security.Claims; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using SuprematyDemo.Domain.Entities; using SuprematyDemo.Infrastructure.Persistence;
namespace SuprematyDemo.Api.Controllers;
[ApiController,Route("api/store")] public sealed class StoreController(AppDbContext db):ControllerBase{
 [HttpGet("products"),AllowAnonymous] public async Task<IActionResult> Products()=>Ok(await db.Products.Where(x=>x.IsActive).OrderByDescending(x=>x.UnitsSold).ToListAsync()); [HttpGet("products/{id:guid}"),AllowAnonymous] public async Task<IActionResult> Product(Guid id)=>await db.Products.FindAsync(id) is { } p?Ok(p):NotFound();
 [HttpGet("top"),AllowAnonymous] public async Task<IActionResult> Top()=>Ok(await db.Products.Where(x=>x.IsActive).OrderByDescending(x=>x.UnitsSold).Take(10).ToListAsync());
 [HttpGet("coupons/{code}/validate"),Authorize] public async Task<IActionResult> ValidateCoupon(string code,[FromQuery]decimal subtotal){var c=await db.Coupons.SingleOrDefaultAsync(c=>c.Code==code.ToUpper()&&c.IsActive);if(c is null)return NotFound(new{message="Coupon code is invalid."});if(c.ExpiresUtc!=null&&c.ExpiresUtc<=DateTimeOffset.UtcNow)return BadRequest(new{message="Coupon has expired."});if(c.MinimumOrder!=null&&subtotal<c.MinimumOrder)return BadRequest(new{message=$"Minimum order is {c.MinimumOrder:0.00}.",minimumOrder=c.MinimumOrder});var discount=decimal.Round(subtotal*c.DiscountPercent/100m,2);return Ok(new{code=c.Code,discountPercent=c.DiscountPercent,discount,subtotal,total=subtotal-discount});}
 [HttpPost("checkout"),Authorize] public async Task<IActionResult> Checkout(CheckoutRequest x){var uid=Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);var ids=x.Items.Select(i=>i.ProductId).ToList();var products=await db.Products.Where(p=>ids.Contains(p.Id)).ToListAsync();if(products.Count!=ids.Distinct().Count())return BadRequest("One or more products are invalid.");decimal subtotal=0;var order=new Order{UserId=uid,CustomerName=x.CustomerName,CustomerEmail=x.CustomerEmail,ShippingAddress=x.ShippingAddress,PaymentMethod=x.PaymentMethod};foreach(var i in x.Items){var p=products.Single(q=>q.Id==i.ProductId);var inv=await db.Inventory.SingleOrDefaultAsync(v=>v.ProductId==p.Id);if(inv is null||i.Quantity<1||inv.QuantityOnHand<i.Quantity)return BadRequest($"Insufficient stock for {p.Name}");var line=p.EffectivePrice*i.Quantity;subtotal+=line;order.Items.Add(new(){ProductId=p.Id,ProductName=p.Name,UnitPrice=p.EffectivePrice,Quantity=i.Quantity});inv.QuantityOnHand-=i.Quantity;p.UnitsSold+=i.Quantity;}decimal discount=0;if(!string.IsNullOrWhiteSpace(x.Coupon)){var c=await db.Coupons.SingleOrDefaultAsync(c=>c.Code==x.Coupon.ToUpper()&&c.IsActive);if(c!=null&&(c.ExpiresUtc==null||c.ExpiresUtc>DateTimeOffset.UtcNow)&&(c.MinimumOrder==null||subtotal>=c.MinimumOrder))discount=subtotal*c.DiscountPercent/100m;}order.Subtotal=subtotal;order.Discount=discount;order.Shipping=subtotal>=100?0:9.99m;order.Total=subtotal-discount+order.Shipping;db.Orders.Add(order);await db.SaveChangesAsync();return Ok(order);}
 [HttpGet("orders"),Authorize] public async Task<IActionResult> MyOrders(){var uid=Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);return Ok(await db.Orders.Include(x=>x.Items).Where(x=>x.UserId==uid).OrderByDescending(x=>x.CreatedUtc).ToListAsync());}
 public record CheckoutItem(Guid ProductId,int Quantity); public record CheckoutRequest(string CustomerName,string CustomerEmail,string ShippingAddress,string PaymentMethod,string? Coupon,List<CheckoutItem> Items);
}
